// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Media.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// Media TABLE
class TableMedia extends SqfEntityTableBase {
  TableMedia() {
    // declare properties of EntityTable
    tableName = 'media';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('path', DbType.text, isNotNull: false),
      SqfEntityFieldBase('userEmail', DbType.text, isNotNull: false),
      SqfEntityFieldBase('userPhone', DbType.text, isNotNull: false),
      SqfEntityFieldBase('adminId', DbType.text, isNotNull: false),
      SqfEntityFieldBase('filename', DbType.text, isNotNull: false),
      SqfEntityFieldBase('createdAt', DbType.datetimeUtc,
          isNotNull: false, minValue: DateTime.parse('1900-01-01')),
      SqfEntityFieldBase('mediaType', DbType.integer,
          defaultValue: 0, isNotNull: false),
      SqfEntityFieldBase('isUploaded', DbType.bool,
          defaultValue: false, isNotNull: false),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableMedia();
  }
}
// END TABLES

// BEGIN DATABASE MODEL
class Eventklip extends SqfEntityModelProvider {
  Eventklip() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    databaseTables = [
      TableMedia.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Media
class Media {
  Media(
      {this.id,
      this.path,
      this.userEmail,
      this.userPhone,
      this.adminId,
      this.filename,
      this.createdAt,
      this.mediaType,
      this.isUploaded,
      this.isDeleted}) {
    _setDefaultValues();
  }
  Media.withFields(
      this.path,
      this.userEmail,
      this.userPhone,
      this.adminId,
      this.filename,
      this.createdAt,
      this.mediaType,
      this.isUploaded,
      this.isDeleted) {
    _setDefaultValues();
  }
  Media.withId(
      this.id,
      this.path,
      this.userEmail,
      this.userPhone,
      this.adminId,
      this.filename,
      this.createdAt,
      this.mediaType,
      this.isUploaded,
      this.isDeleted) {
    _setDefaultValues();
  }
  Media.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['path'] != null) {
      path = o['path'] as String;
    }
    if (o['userEmail'] != null) {
      userEmail = o['userEmail'] as String;
    }
    if (o['userPhone'] != null) {
      userPhone = o['userPhone'] as String;
    }
    if (o['adminId'] != null) {
      adminId = o['adminId'] as String;
    }
    if (o['filename'] != null) {
      filename = o['filename'] as String;
    }
    if (o['createdAt'] != null) {
      createdAt = int.tryParse(o['createdAt'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['createdAt'].toString()),
              isUtc: true)
          : DateTime.tryParse(o['createdAt'].toString());
    }
    if (o['mediaType'] != null) {
      mediaType = int.tryParse(o['mediaType'].toString());
    }
    if (o['isUploaded'] != null) {
      isUploaded = o['isUploaded'] == 1 || o['isUploaded'] == true;
    }
    isDeleted = o['isDeleted'] != null
        ? o['isDeleted'] == 1 || o['isDeleted'] == true
        : null;
  }
  // FIELDS (Media)
  int id;
  String path;
  String userEmail;
  String userPhone;
  String adminId;
  String filename;
  DateTime createdAt;
  int mediaType;
  bool isUploaded;
  bool isDeleted;

  BoolResult saveResult;
  // end FIELDS (Media)

  static const bool _softDeleteActivated = true;
  MediaManager __mnMedia;

  MediaManager get _mnMedia {
    return __mnMedia = __mnMedia ?? MediaManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (path != null) {
      map['path'] = path;
    }

    if (userEmail != null) {
      map['userEmail'] = userEmail;
    }

    if (userPhone != null) {
      map['userPhone'] = userPhone;
    }

    if (adminId != null) {
      map['adminId'] = adminId;
    }

    if (filename != null) {
      map['filename'] = filename;
    }

    if (createdAt != null) {
      map['createdAt'] = forJson
          ? createdAt.toUtc().toString()
          : forQuery ? createdAt.millisecondsSinceEpoch : createdAt;
    }

    if (mediaType != null) {
      map['mediaType'] = mediaType;
    }

    if (isUploaded != null) {
      map['isUploaded'] = forQuery ? (isUploaded ? 1 : 0) : isUploaded;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (path != null) {
      map['path'] = path;
    }

    if (userEmail != null) {
      map['userEmail'] = userEmail;
    }

    if (userPhone != null) {
      map['userPhone'] = userPhone;
    }

    if (adminId != null) {
      map['adminId'] = adminId;
    }

    if (filename != null) {
      map['filename'] = filename;
    }

    if (createdAt != null) {
      map['createdAt'] = forJson
          ? createdAt.toUtc().toString()
          : forQuery ? createdAt.millisecondsSinceEpoch : createdAt;
    }

    if (mediaType != null) {
      map['mediaType'] = mediaType;
    }

    if (isUploaded != null) {
      map['isUploaded'] = forQuery ? (isUploaded ? 1 : 0) : isUploaded;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method returns Json String [Media]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Media]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [
      path,
      userEmail,
      userPhone,
      adminId,
      filename,
      createdAt != null ? createdAt.millisecondsSinceEpoch : null,
      mediaType,
      isUploaded,
      isDeleted
    ];
  }

  List<dynamic> toArgsWithIds() {
    return [
      id,
      path,
      userEmail,
      userPhone,
      adminId,
      filename,
      createdAt != null ? createdAt.millisecondsSinceEpoch : null,
      mediaType,
      isUploaded,
      isDeleted
    ];
  }

  static Future<List<Media>> fromWebUrl(String url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print('SQFENTITY ERROR Media.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(String url, {Map<String, String> headers}) {
    return http.post(url, headers: headers, body: toJson());
  }

  static Future<List<Media>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Media>[];
    try {
      objList = list
          .map((media) => Media.fromMap(media as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Media.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Media>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<Media> objList = <Media>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Media.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Media by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Media if exist, otherwise returns null
  Future<Media> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Media obj;
    final data = await _mnMedia.getById([id]);
    if (data.length != 0) {
      obj = Media.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Media) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnMedia.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnMedia.update(this);
    }

    return id;
  }

  /// saveAs Media. Returns a new Primary Key value of Media

  /// <returns>Returns a new Primary Key value of Media
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Media> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Media> medias) async {
    // final results = _mnMedia.saveAll('INSERT OR REPLACE INTO media (id,path, userEmail, userPhone, adminId, filename, createdAt, mediaType, isUploaded,isDeleted)  VALUES (?,?,?,?,?,?,?,?,?,?)',medias);
    // return results; removed in sqfentity_gen 1.3.0+6
    await Eventklip().batchStart();
    for (final obj in medias) {
      await obj.save();
    }
    //    return Eventklip().batchCommit();
    final result = await Eventklip().batchCommit();
    for (int i = 0; i < medias.length; i++) {
      if (medias[i].id == null) {
        medias[i].id = result[i] as int;
      }
    }

    return result;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnMedia.rawInsert(
              'INSERT OR REPLACE INTO media (id,path, userEmail, userPhone, adminId, filename, createdAt, mediaType, isUploaded,isDeleted)  VALUES (?,?,?,?,?,?,?,?,?,?)',
              [
                id,
                path,
                userEmail,
                userPhone,
                adminId,
                filename,
                createdAt != null ? createdAt.millisecondsSinceEpoch : null,
                mediaType,
                isUploaded,
                isDeleted
              ]) ==
          1) {
        saveResult = BoolResult(
            success: true, successMessage: 'Media id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Media id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Media Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Media>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Media> medias) async {
    final results = await _mnMedia.rawInsertAll(
        'INSERT OR REPLACE INTO media (id,path, userEmail, userPhone, adminId, filename, createdAt, mediaType, isUploaded,isDeleted)  VALUES (?,?,?,?,?,?,?,?,?,?)',
        medias);
    return results;
  }

  /// Deletes Media

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Media invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted) {
      return _mnMedia
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnMedia.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover Media>

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    print('SQFENTITIY: recover Media invoked (id=$id)');
    {
      return _mnMedia.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  MediaFilterBuilder select({List<String> columnsToSelect, bool getIsDeleted}) {
    return MediaFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  MediaFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return MediaFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    mediaType = mediaType ?? 0;
    isUploaded = isUploaded ?? false;
    isDeleted = isDeleted ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion media

// region MediaField
class MediaField extends SearchCriteria {
  MediaField(this.mediaFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  MediaFilterBuilder mediaFB;

  MediaField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  MediaFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    mediaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, mediaFB.parameters, param, SqlSyntax.EQuals,
            mediaFB._addedBlocks)
        : setCriteria(pValue, mediaFB.parameters, param, SqlSyntax.NotEQuals,
            mediaFB._addedBlocks);
    _waitingNot = '';
    mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
        mediaFB._addedBlocks.retVal;
    return mediaFB;
  }

  MediaFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    mediaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, mediaFB.parameters, param, SqlSyntax.EQualsOrNull,
            mediaFB._addedBlocks)
        : setCriteria(pValue, mediaFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, mediaFB._addedBlocks);
    _waitingNot = '';
    mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
        mediaFB._addedBlocks.retVal;
    return mediaFB;
  }

  MediaFilterBuilder isNull() {
    mediaFB._addedBlocks = setCriteria(
        0,
        mediaFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        mediaFB._addedBlocks);
    _waitingNot = '';
    mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
        mediaFB._addedBlocks.retVal;
    return mediaFB;
  }

  MediaFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      mediaFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          mediaFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          mediaFB._addedBlocks);
      _waitingNot = '';
      mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
          mediaFB._addedBlocks.retVal;
    }
    return mediaFB;
  }

  MediaFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      mediaFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          mediaFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          mediaFB._addedBlocks);
      _waitingNot = '';
      mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
          mediaFB._addedBlocks.retVal;
      mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
          mediaFB._addedBlocks.retVal;
    }
    return mediaFB;
  }

  MediaFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      mediaFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          mediaFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          mediaFB._addedBlocks);
      _waitingNot = '';
      mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
          mediaFB._addedBlocks.retVal;
    }
    return mediaFB;
  }

  MediaFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      mediaFB._addedBlocks = setCriteria(
          pFirst,
          mediaFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          mediaFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        mediaFB._addedBlocks = setCriteria(pFirst, mediaFB.parameters, param,
            SqlSyntax.LessThan, mediaFB._addedBlocks);
      } else {
        mediaFB._addedBlocks = setCriteria(pFirst, mediaFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, mediaFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        mediaFB._addedBlocks = setCriteria(pLast, mediaFB.parameters, param,
            SqlSyntax.GreaterThan, mediaFB._addedBlocks);
      } else {
        mediaFB._addedBlocks = setCriteria(pLast, mediaFB.parameters, param,
            SqlSyntax.LessThanOrEquals, mediaFB._addedBlocks);
      }
    }
    _waitingNot = '';
    mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
        mediaFB._addedBlocks.retVal;
    return mediaFB;
  }

  MediaFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    mediaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, mediaFB.parameters, param, SqlSyntax.GreaterThan,
            mediaFB._addedBlocks)
        : setCriteria(pValue, mediaFB.parameters, param,
            SqlSyntax.LessThanOrEquals, mediaFB._addedBlocks);
    _waitingNot = '';
    mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
        mediaFB._addedBlocks.retVal;
    return mediaFB;
  }

  MediaFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    mediaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, mediaFB.parameters, param, SqlSyntax.LessThan,
            mediaFB._addedBlocks)
        : setCriteria(pValue, mediaFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, mediaFB._addedBlocks);
    _waitingNot = '';
    mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
        mediaFB._addedBlocks.retVal;
    return mediaFB;
  }

  MediaFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    mediaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, mediaFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, mediaFB._addedBlocks)
        : setCriteria(pValue, mediaFB.parameters, param, SqlSyntax.LessThan,
            mediaFB._addedBlocks);
    _waitingNot = '';
    mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
        mediaFB._addedBlocks.retVal;
    return mediaFB;
  }

  MediaFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    mediaFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, mediaFB.parameters, param,
            SqlSyntax.LessThanOrEquals, mediaFB._addedBlocks)
        : setCriteria(pValue, mediaFB.parameters, param, SqlSyntax.GreaterThan,
            mediaFB._addedBlocks);
    _waitingNot = '';
    mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
        mediaFB._addedBlocks.retVal;
    return mediaFB;
  }

  MediaFilterBuilder inValues(dynamic pValue) {
    mediaFB._addedBlocks = setCriteria(
        pValue,
        mediaFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        mediaFB._addedBlocks);
    _waitingNot = '';
    mediaFB._addedBlocks.needEndBlock[mediaFB._blockIndex] =
        mediaFB._addedBlocks.retVal;
    return mediaFB;
  }
}
// endregion MediaField

// region MediaFilterBuilder
class MediaFilterBuilder extends SearchCriteria {
  MediaFilterBuilder(Media obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Media _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  MediaFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  MediaFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  MediaFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  MediaFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  MediaFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  MediaFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  MediaFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  MediaFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  MediaFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  MediaFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  MediaFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  MediaField setField(MediaField field, String colName, DbType dbtype) {
    return MediaField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  MediaField _id;
  MediaField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  MediaField _path;
  MediaField get path {
    return _path = setField(_path, 'path', DbType.text);
  }

  MediaField _userEmail;
  MediaField get userEmail {
    return _userEmail = setField(_userEmail, 'userEmail', DbType.text);
  }

  MediaField _userPhone;
  MediaField get userPhone {
    return _userPhone = setField(_userPhone, 'userPhone', DbType.text);
  }

  MediaField _adminId;
  MediaField get adminId {
    return _adminId = setField(_adminId, 'adminId', DbType.text);
  }

  MediaField _filename;
  MediaField get filename {
    return _filename = setField(_filename, 'filename', DbType.text);
  }

  MediaField _createdAt;
  MediaField get createdAt {
    return _createdAt = setField(_createdAt, 'createdAt', DbType.datetimeUtc);
  }

  MediaField _mediaType;
  MediaField get mediaType {
    return _mediaType = setField(_mediaType, 'mediaType', DbType.integer);
  }

  MediaField _isUploaded;
  MediaField get isUploaded {
    return _isUploaded = setField(_isUploaded, 'isUploaded', DbType.bool);
  }

  MediaField _isDeleted;
  MediaField get isDeleted {
    return _isDeleted = setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Media._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<Media> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (Media._softDeleteActivated && !hardDelete) {
      r = await _obj._mnMedia.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnMedia.delete(qparams);
    }
    return r;
  }

  /// Recover List<Media> bulk by query
  Future<BoolResult> recover() async {
    _getIsDeleted = true;
    _buildParameters();
    print('SQFENTITIY: recover Media bulk invoked');
    return _obj._mnMedia.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from media ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnMedia.updateBatch(qparams, values);
  }

  /// This method always returns Media Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Media>
  Future<Media> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnMedia.toList(qparams);
    final data = await objFuture;
    Media obj;
    if (data.isNotEmpty) {
      obj = Media.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [Media]
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) mediaCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final mediasFuture = await _obj._mnMedia.toList(qparams);
    final int count = mediasFuture[0]['CNT'] as int;
    if (mediaCount != null) {
      mediaCount(count);
    }
    return count;
  }

  /// This method returns List<Media> [Media]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Media>
  Future<List<Media>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Media> mediasData = await Media.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return mediasData;
  }

  /// This method returns Json String [Media]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Media]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Media]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnMedia.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Media]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM media WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnMedia.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Media]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnMedia.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Media.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnMedia.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion MediaFilterBuilder

// region MediaFields
class MediaFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fPath;
  static TableField get path {
    return _fPath = _fPath ?? SqlSyntax.setField(_fPath, 'path', DbType.text);
  }

  static TableField _fUserEmail;
  static TableField get userEmail {
    return _fUserEmail = _fUserEmail ??
        SqlSyntax.setField(_fUserEmail, 'userEmail', DbType.text);
  }

  static TableField _fUserPhone;
  static TableField get userPhone {
    return _fUserPhone = _fUserPhone ??
        SqlSyntax.setField(_fUserPhone, 'userPhone', DbType.text);
  }

  static TableField _fAdminId;
  static TableField get adminId {
    return _fAdminId =
        _fAdminId ?? SqlSyntax.setField(_fAdminId, 'adminId', DbType.text);
  }

  static TableField _fFilename;
  static TableField get filename {
    return _fFilename =
        _fFilename ?? SqlSyntax.setField(_fFilename, 'filename', DbType.text);
  }

  static TableField _fCreatedAt;
  static TableField get createdAt {
    return _fCreatedAt = _fCreatedAt ??
        SqlSyntax.setField(_fCreatedAt, 'createdAt', DbType.datetimeUtc);
  }

  static TableField _fMediaType;
  static TableField get mediaType {
    return _fMediaType = _fMediaType ??
        SqlSyntax.setField(_fMediaType, 'mediaType', DbType.integer);
  }

  static TableField _fIsUploaded;
  static TableField get isUploaded {
    return _fIsUploaded = _fIsUploaded ??
        SqlSyntax.setField(_fIsUploaded, 'isUploaded', DbType.bool);
  }

  static TableField _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion MediaFields

//region MediaManager
class MediaManager extends SqfEntityProvider {
  MediaManager()
      : super(Eventklip(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'media';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion MediaManager
class EventklipSequenceManager extends SqfEntityProvider {
  EventklipSequenceManager() : super(Eventklip());
}
// END OF ENTITIES
